### ISSUE TITLE
Need help getting p2pool-scanner to run

### ISSUE THREAD

**Issue by mahrens917** [litecoin-project/p2pool-scanner#5]
I need help getting p2pool-scanner running.  I am sure I am missing something simple.  Please help.

When I run 

```
 nodes scanner.js 
```

I get:

```
module.js:340
throw err;
      ^
Error: Cannot find module 'underscore'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous> (/home/ubuntu/p2pool/web-static/p2pool-scanner/scanner.js:5:6)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Function.Module.runMain (module.js:497:10)
```

If I add this line to my code

```
<script src="p2pool-scanner/scanner.js"></script>
```

I get:

```
[Error] ReferenceError: Can't find variable: require
    global code (scanner.js, line 3)
```

**Comment by theknightorc** [comment]
Here are the docs I put together for my buddies coin.

https://github.com/theknightorc/p2pool-candycoin/blob/master/p2pool-scanner/INSTALL
